site_name: quiCAT
repo_url: https://github.com/theislab/quicat
site_url: https://quicat.readthedocs.io/
site_description: Clonal Analays Toolkit - quicat
site_author: Daniele Lucarelli
edit_uri: edit/main/docs/
repo_name: theislab/quicat

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Principles:
      - Overview: usage/usage.md
      - extract: usage/extract.md
      - simulate: usage/simulate.md
  - API:
      - Overview: api/api.md
      - Read: api/read.md
      - Plotting: api/plotting.md
      - Tools: api/tools.md
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          paths: [src]
          docstring_style: google
          options:
            show_root_heading: true
            heading_level: 4

theme:
  name: material
  logo: assets/quicat_logo.svg
  favicon: assets/quicat_logo.svg
  feature:
    tabs: true
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.code.select
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theislab/quicat
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/quicat

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
