name: release-main

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install

      - name: Run checks
        run: make check

      - name: Run tests
        run: make test

      - name: Build and publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: make build-and-publish

  deploy-docs:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ReadTheDocs Build
        env:
          READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
          READTHEDOCS_PROJECT: quicat # Replace with your RTD project slug
        run: |
          curl -X POST \
            -H "Authorization: Token $READTHEDOCS_TOKEN" \
            https://readthedocs.org/api/v3/webhook/$READTHEDOCS_PROJECT/
